### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by mwpwalshe** [sachink2010/AutomatedStockTrading-DeepQ-Learning#1]
All Models are empty?
Can you re- upload?
Michael

**Comment by sachink2010** [comment]
hi Michael,
Thanks for pointing out. model.py file is not needed. I have deleted it. Models that are saved during training phase are model_ep0, model_ep10 etc. These models can be pre-loaded to test the test data.
Please let me know if you find any other issues.
Regards,
Sachin
