### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by SergioSV96** [sachink2010/AutomatedStockTrading-DeepQ-Learning#3]
Thanks for your work, I like your approach for trading stocks, could this be ported to **trading cryptocurrencies** instead?

What are your thoughts on this, are there any better approaches than DeepQLearning?

Thanks in advance!

**Comment by sachink2010** [comment]
Thanks for your positive feedback. I am not a seasoned programmer, started to learn Machine Learning, so these postive comments gives extra motivation to do more :-)

Regarding your comment on possibility of using above approach for cryptocurrencies, yes it is indeed possible to do it. There are few problems I see: 
1. cryptocurrencies are quite new, so there is not as much data as normal stocks for robot to learn. 
2. Price volatility in crypto can be too high. Bitcoin shot up to $20,000 then fell to $1000, and now again around $10,000. So, it might not be easy for robot to decide when to buy/sell
But, I like the idea, so may be it can be tested with atleast the important cryptos like Bitcoin, Ether, Litecoin etc. I would be hesitant to use it on smaller market cap cryptos.
