### ISSUE TITLE
Is it possible to design this kind of agents?

### ISSUE THREAD

**Issue by alanyuwenche** [sachink2010/AutomatedStockTrading-DeepQ-Learning#6]
Happy New Year!

In this model you set certain amounts of equities in the initial portfolio. Therefore, the agent can first start buying or selling equities. But some markets like forex, you can start buying or selling even without any position. Is it possible to design this kind of agents? Thank you very much!

**Comment by sachink2010** [comment]
Thanks for the wishes. Happy  New Year to you too!!
Sorry for late response.
I agree with you that there are not all markets where there would be initial amount  to start with. It should be possible to design agent that would work with zero initial amount. Based on my limited knowledge on the topic, I feel what needs to be carefully designed is:
-  State (this should have right information to make a decision): In my case I choose last 5 days prices and today's price, quantity of stock. For Forex market, may be some other parameters might be suitable 
- Reward Function: This should be such that if agent goes bankrupt, then a huge negative reward should be given. If starting with zero amount, then chances of going bankrupt are more, so this needs to be thought of.
- Training time: I used Google Colab free GPU for training and there had a limitation of time. With zero initial amount, agent might  need more time to learn what is right action
What do you think?

**Comment by alanyuwenche** [comment]
Thanks for your suggestion.

Training time depends on data amount and the number of training epochs. RL is a sample-inefficient algorithm, which needs a lot of data. It’s not so difficult to collect enough daily data, but it’s not easy for intraday data. Besides, the more training epochs don’t always produce better performance. What do you think about it?
