### ISSUE TITLE
Agent does not learn from actions

### ISSUE THREAD

**Issue by TheChronicler** [sachink2010/AutomatedStockTrading-DeepQ-Learning#8]
As far as I understand it there is a typo in the following line: https://github.com/sachink2010/AutomatedStockTrading-DeepQ-Learning/blob/424e58dc0a84fac07db3f624bb6f0bd3b96d3792/agent/agent.py#L50
`minibatch` is used instead of `mini_batch` so the for-loop is not called and thus the model.fit method will never be called

**Comment by sachink2010** [comment]
hello, thanks for your comment. I don't know how it was missed, probably copy-paste error. I have updated it.
